[package]
org = "ai_samples"
name = "compare_similarity_using_embeddings"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "openai.embeddings"
version = "0.1.0"
repository = "local"
